// T-C1 + corpus generator behaviour tests (implementation specification §11;
// §17 step 2 gate). The corpus under pitch-lab/assets/corpus/ is COMMITTED
// (authoritative inputs, §11.1) — this test regenerates every item from
// config/corpus.toml and asserts:
//   * T-C1 (spec §11.4): regeneration BIT-IDENTITY — same-binary, in-process
//     double generation (pure determinism of the generator), AND bit-exact
//     equality with the COMMITTED corpus WAVs (read back through the §9
//     reader). Cross-platform note: the committed corpus is generated by the
//     development build; if a CI runner's libm ever disagrees by 1 ulp this
//     comparison will fail LOUDLY (that is the gate working — the finding
//     would be recorded, not silently tolerated).
//   * itemSeed derivation golden (the frozen §11.4 rule).
//   * metadata.toml parses with the §15.5 fields and honest values.
//   * -12 dBFS true-peak normalisation (exact-signal scaling, §11.2).
//   * light recipe sanity probes (sine dominant frequency via Goertzel,
//     noise mean ~ 0, correlated stereo bit-identical channels,
//     decorrelated stereo differing, pink LF/HF energy ratio).

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "core/corpus_gen.h"
#include "core/errors.h"
#include "core/rng.h"
#include "core/toml_lite.h"
#include "core/wav_io.h"

#ifndef PITCHLAB_SOURCE_DIR
#error "PITCHLAB_SOURCE_DIR must be defined by CMake for this test"
#endif

namespace {

const std::filesystem::path kSourceDir = PITCHLAB_SOURCE_DIR;
const std::filesystem::path kCorpusDir = kSourceDir / "assets" / "corpus";
const std::filesystem::path kConfigFile = kSourceDir / "config" / "corpus.toml";

}  // namespace

TEST_CASE("T-C1: corpus regeneration bit-identity + committed-corpus equality") {
  const auto config = pitchlab::parseCorpusConfig(kConfigFile);
  REQUIRE(config.items.size() == 17);
  REQUIRE(config.masterSeed == 0x50E5A1AB);

  const auto gen1 = pitchlab::generateCorpus(config);
  const auto gen2 = pitchlab::generateCorpus(config);
  REQUIRE(gen1.size() == config.items.size());

  for (std::size_t i = 0; i < gen1.size(); ++i) {
    const auto& a = gen1[i];
    const auto& b = gen2[i];
    REQUIRE(a.channels.size() == b.channels.size());
    for (std::size_t c = 0; c < a.channels.size(); ++c) {
      REQUIRE(a.channels[c].size() == b.channels[c].size());
      // same-binary in-process regeneration: bit-identical
      CHECK(std::memcmp(a.channels[c].data(), b.channels[c].data(),
                        a.channels[c].size() * sizeof(double)) == 0);
    }
  }

  // The committed corpus must match the regeneration bit-exactly.
  for (const auto& item : gen1) {
    const auto wavPath = kCorpusDir / item.spec.id / "signal.wav";
    if (!std::filesystem::exists(wavPath)) {
      FAIL_CHECK("committed corpus file missing: " << wavPath.string());
      continue;
    }
    const auto wav = pitchlab::readWav(wavPath);
    REQUIRE(wav.channels.size() == item.channels.size());
    REQUIRE(wav.meta.frames == static_cast<pitchlab::FrameCount>(item.channels[0].size()));
    REQUIRE(wav.meta.sampleRate == static_cast<uint32_t>(item.spec.sampleRate));
    REQUIRE(wav.meta.channels == item.spec.channels);
    REQUIRE(wav.meta.bitsPerSample == 64);
    for (std::size_t c = 0; c < item.channels.size(); ++c) {
      const bool identical =
          std::memcmp(wav.channels[c].data(), item.channels[c].data(),
                      item.channels[c].size() * sizeof(double)) == 0;
      CHECK_MESSAGE(identical, item.spec.id << " channel " << c
                                            << " differs from the committed corpus");
    }
  }
}

TEST_CASE("T-C1b: itemSeed derivation golden (frozen §11.4 rule)") {
  // itemSeed = splitMix64(masterSeed XOR fnv1a64(itemId)) — value captured
  // from the implementation 2026-09-26 (regression pin against accidental
  // rule changes; the rule composition is also cross-checked via primitives).
  const uint64_t master = 0x50E5A1ABULL;
  const std::string id = "syn-sine-440-5s-44k1";
  CHECK(pitchlab::corpusItemSeed(master, id) == 8748028519920161202ULL);
  CHECK(pitchlab::corpusItemSeed(master, id) ==
        pitchlab::splitMix64(master ^ pitchlab::fnv1a64(id.c_str())));
}

TEST_CASE("T-C1c: metadata.toml — §15.5 fields with honest values") {
  const auto config = pitchlab::parseCorpusConfig(kConfigFile);
  const auto items = pitchlab::generateCorpus(config);
  for (const auto& item : items) {
    const auto metaPath = kCorpusDir / item.spec.id / "metadata.toml";
    if (!std::filesystem::exists(metaPath)) {
      FAIL_CHECK("committed metadata missing: " << metaPath.string());
      continue;
    }
    const auto meta = pitchlab::toml::parseTomlFile(metaPath);
    REQUIRE(meta.at("id").asString(metaPath.string(), "id") == item.spec.id);
    REQUIRE(meta.at("category").asString(metaPath.string(), "category") ==
            item.spec.category);
    REQUIRE(meta.at("sampleRate").asInteger(metaPath.string(), "sampleRate") ==
            static_cast<int64_t>(item.spec.sampleRate));
    REQUIRE(meta.at("channels").asInteger(metaPath.string(), "channels") ==
            item.spec.channels);
    REQUIRE(meta.at("durationSec").asDouble(metaPath.string(), "durationSec") ==
            doctest::Approx(item.spec.durationSec));
    REQUIRE(meta.at("sourceDescription").asString(metaPath.string(), "sourceDescription") ==
            item.sourceDescription);
    REQUIRE(meta.at("referenceStatus").asString(metaPath.string(), "referenceStatus") ==
            "test-fixture");
    const auto& band = meta.at("bandContentHz").asArray(metaPath.string(), "bandContentHz");
    REQUIRE(band.size() == 2);
    REQUIRE(band[0].asDouble(metaPath.string(), "bandContentHz") ==
            doctest::Approx(item.bandContentHz[0]));
    REQUIRE(band[1].asDouble(metaPath.string(), "bandContentHz") ==
            doctest::Approx(item.bandContentHz[1]));
    REQUIRE(band[0].asDouble(metaPath.string(), "bandContentHz") > 0.0);
    REQUIRE(band[1].asDouble(metaPath.string(), "bandContentHz") >=
            band[0].asDouble(metaPath.string(), "bandContentHz"));
  }
}

TEST_CASE("T-C1d: -12 dBFS true-peak normalisation (exact-signal scaling)") {
  const auto config = pitchlab::parseCorpusConfig(kConfigFile);
  const auto items = pitchlab::generateCorpus(config);
  const double target = std::pow(10.0, -12.0 / 20.0);
  for (const auto& item : items) {
    double peak = 0.0;
    for (const auto& ch : item.channels) {
      for (double v : ch) peak = std::max(peak, std::fabs(v));
    }
    CHECK_MESSAGE(std::fabs(peak - target) < 1e-12 * 4.0,
                  item.spec.id << ": normalised peak " << peak << " vs target " << target);
    CHECK(item.peakLinear > 0.0);
  }
}

TEST_CASE("T-C1e: recipe sanity probes (light, structural)") {
  const auto config = pitchlab::parseCorpusConfig(kConfigFile);
  const auto items = pitchlab::generateCorpus(config);
  auto findItem = [&](const std::string& id) -> const pitchlab::GeneratedCorpusItem* {
    for (const auto& it : items) {
      if (it.spec.id == id) return &it;
    }
    return static_cast<const pitchlab::GeneratedCorpusItem*>(nullptr);
  };

  // sine 440 @ 48k: Goertzel probe at 440 Hz vs neighbours — dominant tone.
  {
    const auto* sine = findItem("syn-sine-440-5s-48k");
    REQUIRE(sine != nullptr);
    const auto& x = sine->channels[0];
    const double fs = 48000.0;
    auto goertzel = [&](double f) {
      const double w = 2.0 * 3.14159265358979323846 * f / fs;
      const double cw = 2.0 * std::cos(w);
      double s0 = 0.0, s1 = 0.0, s2 = 0.0;
      for (double v : x) {
        s0 = v + cw * s1 - s2;
        s2 = s1;
        s1 = s0;
      }
      return std::sqrt(s1 * s1 + s2 * s2 - cw * s1 * s2);
    };
    const double at440 = goertzel(440.0);
    const double at400 = goertzel(400.0);
    const double at480 = goertzel(480.0);
    CHECK(at440 > at400 * 10.0);
    CHECK(at440 > at480 * 10.0);
  }

  // white noise: mean ~ 0 (5 s of samples).
  {
    const auto* noise = findItem("syn-noise-white-5s-48k");
    REQUIRE(noise != nullptr);
    double mean = 0.0;
    for (double v : noise->channels[0]) mean += v;
    mean /= static_cast<double>(noise->channels[0].size());
    CHECK(std::fabs(mean) < 0.01);
  }

  // pink noise: LF energy dominates HF energy (Voss character).
  {
    const auto* pink = findItem("syn-noise-pink-5s-48k");
    REQUIRE(pink != nullptr);
    const auto& x = pink->channels[0];
    // crude 1-pole splitters: energy below ~1 kHz vs above ~5 kHz.
    const double fs = 48000.0;
    auto energy = [&](double lo, double hi) {
      // box-filter difference energy via simple FIR differencing of a
      // moving average (deterministic, coarse).
      const int n1 = std::max(1, static_cast<int>(fs / lo));
      const int n2 = std::max(1, static_cast<int>(fs / hi));
      double acc = 0.0;
      for (std::size_t i = static_cast<std::size_t>(n2); i < x.size() - n1; ++i) {
        double m1 = 0.0;
        for (int k = 0; k < n1; ++k) m1 += x[i + k];
        double m2 = 0.0;
        for (int k = 0; k < n2; ++k) m2 += x[i + k];
        const double band = m1 / n1 - m2 / n2;
        acc += band * band;
      }
      return acc;
    };
    // pink = equal energy per octave: compare a 3-octave LF band against a
    // 1-octave HF band (expected ratio ~3; threshold 2).
    CHECK(energy(50.0, 400.0) > energy(5000.0, 10000.0) * 2.0);
  }

  // correlated stereo: channels bit-identical; decorrelated: differ.
  {
    const auto* corr = findItem("syn-stereo-correlated-noise-5s-48k");
    REQUIRE(corr != nullptr);
    CHECK(std::memcmp(corr->channels[0].data(), corr->channels[1].data(),
                      corr->channels[0].size() * sizeof(double)) == 0);
    const auto* decor = findItem("syn-stereo-decorrelated-noise-5s-48k");
    REQUIRE(decor != nullptr);
    bool anyDifferent = false;
    for (std::size_t i = 0; i < decor->channels[0].size(); ++i) {
      if (decor->channels[0][i] != decor->channels[1][i]) anyDifferent = true;
    }
    CHECK(anyDifferent);
    // shared envelope: channel RMS magnitudes are close (same envelope).
    auto rms = [](const std::vector<double>& v) {
      double acc = 0.0;
      for (double x : v) acc += x * x;
      return std::sqrt(acc / static_cast<double>(v.size()));
    };
    const double rl = rms(decor->channels[0]), rr = rms(decor->channels[1]);
    CHECK(std::fabs(rl - rr) / rr < 0.05);
  }

  // impulse train: non-zero frames land on the 1 ms grid (48-sample spacing).
  {
    const auto* imp = findItem("syn-transient-impulses-2s-48k");
    REQUIRE(imp != nullptr);
    const auto& x = imp->channels[0];
    int count = 0;
    for (std::size_t i = 0; i < x.size(); ++i) {
      if (x[i] != 0.0) {
        ++count;
        CHECK((i % 48) == 0);
      }
    }
    CHECK(count == 2000);  // 2 s at 1000 impulses/s
  }

  // sweep: instantaneous frequency near 20 Hz at the start (phase slope).
  {
    const auto* sw = findItem("syn-sweep-log-20-10800-4s-48k");
    REQUIRE(sw != nullptr);
    const auto& x = sw->channels[0];
    const double fs = 48000.0;
    // average |dx/dt| over the first 2000 frames vs a 20 Hz sine's slope.
    double slope = 0.0;
    for (std::size_t i = 1; i < 2000; ++i) {
      slope += std::fabs(x[i] - x[i - 1]);
    }
    slope /= 1999.0;
    // mean |sin slope| = 2/pi * 2*pi*f/fs, scaled by the -12 dBFS
    // normalisation (target peak 10^(-12/20)); generous band (log sweep).
    const double target = std::pow(10.0, -12.0 / 20.0);
    const double expect =
        2.0 * 3.14159265358979323846 * 20.0 / fs * 2.0 / 3.14159265358979323846 * target;
    CHECK(slope > expect * 0.5);
    CHECK(slope < expect * 1.5);
  }
}

TEST_CASE("T-C1f: corpus config validation rejects bad configs") {
  const std::filesystem::path tmpDir =
      std::filesystem::temp_directory_path() / "pitchlab-corpus-test";
  std::filesystem::create_directories(tmpDir);
  auto writeConfig = [&](const std::string& name, const std::string& text) {
    const auto p = tmpDir / name;
    std::ofstream out(p, std::ios::binary);
    out << text;
    return p;
  };
  struct Case {
    const char* name;
    std::string text;
    std::string fieldSub;
  };
  const Case cases[] = {
      {"unknown version", "version = \"v9.9\"\nmasterSeed = 1\n", "version"},
      {"missing masterSeed", "version = \"v0.1\"\n", "masterSeed"},
      {"unknown class",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"gong\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 1\nparams = { }\n",
       "class"},
      {"unsupported rate",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sine\"\n"
       "sampleRate = 44101\ndurationSec = 1.0\nchannels = 1\nparams = { freqHz = 440.0 }\n",
       "sampleRate"},
      {"channel mismatch",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sine\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 2\nparams = { freqHz = 440.0 }\n",
       "channels"},
      {"missing param",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sine\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 1\nparams = { }\n",
       "freqHz"},
      {"unknown param key",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sine\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 1\nparams = { freqHz = 440.0, "
       "colour = 1.0 }\n",
       "colour"},
      {"duplicate id",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sine\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 1\nparams = { freqHz = 440.0 }\n"
       "[[item]]\nid = \"x\"\nclass = \"sine\"\nsampleRate = 48000\ndurationSec = 1.0\n"
       "channels = 1\nparams = { freqHz = 440.0 }\n",
       "id"},
      {"sweep above Nyquist",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sweep-log\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 1\nparams = { startHz = 20.0, "
       "endHz = 24000.0 }\n",
       "endHz"},
      {"unknown item key",
       "version = \"v0.1\"\nmasterSeed = 1\n[[item]]\nid = \"x\"\nclass = \"sine\"\n"
       "sampleRate = 48000\ndurationSec = 1.0\nchannels = 1\nparams = { freqHz = 440.0 }\n"
       "colour = 3\n",
       "colour"},
  };
  for (const auto& c : cases) {
    const auto path = writeConfig("bad.toml", c.text);
    bool threw = false;
    std::string field;
    try {
      (void)pitchlab::parseCorpusConfig(path);
    } catch (const pitchlab::ConfigError& e) {
      threw = true;
      field = e.field();
    }
    CHECK_MESSAGE(threw, c.name);
    if (threw) {
      CHECK_MESSAGE(field.find(c.fieldSub) != std::string::npos,
                    c.name << ": expected field containing '" << c.fieldSub << "', got '"
                           << field << "'");
    }
  }
}
