#pragma once

// Pitch Lab VST3 product layer — the plug-in processor (single-component
// effect: IComponent + IEditController + IAudioProcessor in one class,
// specification §2/§8).
//
// Layering: DAW -> this processor -> RealtimeAdapter -> v0.1 engines.
// No DSP lives here: parameter registration from the ONE model
// (parameters.h), state, bus/latency/host behaviour, and the process()
// boundary conversion (32/64 <-> the adapter's double path).

#include <atomic>
#include <memory>

#include "public.sdk/source/vst/vstsinglecomponenteffect.h"
#include "vst/parameters.h"
#include "vst/realtime_adapter.h"
#include "vst/view_interfaces.h"

namespace pitchlab::vst {

// The plug-in's fixed class identity (FUID).
extern const Steinberg::FUID PitchLabProcessorUID;

class PitchLabProcessor final : public Steinberg::Vst::SingleComponentEffect,
                                public IPitchLabMeters,
                                public IPitchLabStatus {
 public:
  PitchLabProcessor();
  ~PitchLabProcessor() override;

  static Steinberg::FUnknown* createInstance(void* /*context*/);

  // ---- IPluginBase ---------------------------------------------------------
  Steinberg::tresult PLUGIN_API initialize(Steinberg::FUnknown* context) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API terminate() SMTG_OVERRIDE;

  // ---- IComponent ------------------------------------------------------------
  Steinberg::tresult PLUGIN_API setActive(Steinberg::TBool state) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API setState(Steinberg::IBStream* state) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API getState(Steinberg::IBStream* state) SMTG_OVERRIDE;

  // ---- IAudioProcessor ---------------------------------------------------------
  Steinberg::tresult PLUGIN_API setBusArrangements(Steinberg::Vst::SpeakerArrangement* inputs,
                                                   Steinberg::int32 numIns,
                                                   Steinberg::Vst::SpeakerArrangement* outputs,
                                                   Steinberg::int32 numOuts) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API canProcessSampleSize(Steinberg::int32 symbolicSampleSize) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API setupProcessing(Steinberg::Vst::ProcessSetup& setup) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API setProcessing(Steinberg::TBool state) SMTG_OVERRIDE;
  Steinberg::tresult PLUGIN_API process(Steinberg::Vst::ProcessData& data) SMTG_OVERRIDE;
  Steinberg::uint32 PLUGIN_API getLatencySamples() SMTG_OVERRIDE;

  // ---- IEditController --------------------------------------------------------
  Steinberg::tresult PLUGIN_API setParamNormalized(Steinberg::Vst::ParamID tag,
                                                   Steinberg::Vst::ParamValue value) SMTG_OVERRIDE;
  Steinberg::IPlugView* PLUGIN_API createView(const Steinberg::char8* name) SMTG_OVERRIDE;

  // ---- view interfaces (editor polling; §7) -------------------------------------
  MetersSnapshot PLUGIN_API getMeters() override { return adapter_.meters(); }
  StatusSnapshot PLUGIN_API getStatus() override { return adapter_.status(); }

  // ---- FUnknown -----------------------------------------------------------------
  // queryInterface is generated by the interface table below (OBJ_METHODS/
  // DEFINE_INTERFACES — the SDK FObject pattern, delegating to the base).

  OBJ_METHODS(PitchLabProcessor, SingleComponentEffect)
  DEFINE_INTERFACES
  DEF_INTERFACE(IPitchLabMeters)
  DEF_INTERFACE(IPitchLabStatus)
  END_DEFINE_INTERFACES(SingleComponentEffect)
  REFCOUNT_METHODS(SingleComponentEffect)

 private:
  // Build the runtime snapshot from the registered parameters (ONE mapping,
  // parameters.h::applyNormalised).
  [[nodiscard]] ParamSnapshot buildSnapshot() const;

  // Publish the snapshot to the adapter (main thread).
  void publishSnapshot();

  // Recompute the expected latency, update reportedLatency_ and notify the
  // host via IComponentHandler::restartComponent(kLatencyChanged) when it
  // changed (MAIN THREAD ONLY — the audio thread never calls the host).
  void updateAndNotifyLatency();

  // The typed process path (Sample32/float and Sample64/double).
  template <typename SampleType>
  Steinberg::tresult processTyped(Steinberg::Vst::ProcessData& data);

  // Extract the block automation from the VST3 parameter queues (audio
  // thread). ONE scan per host block, BLOCK-RELATIVE coordinates (the
  // authoritative VST3 domain); per-chunk slices are produced by
  // sliceAutomation (each event converted exactly once, never clamped
  // across chunk boundaries).
  void collectBlockAutomation(Steinberg::Vst::ProcessData& data, int32_t blockFrames);

  // Rebase the block-relative events into the owning processor chunk's
  // local coordinates (audio thread, allocation-free).
  static void sliceAutomation(const BlockAutomation& block, int32_t chunkBase,
                              int32_t chunkFrames, BlockAutomation& out);

  RealtimeAdapter adapter_;
  std::atomic<uint32_t> reportedLatency_{0};
  std::atomic<bool> processingSuspended_{false};

  // Audio-thread scratch for the block-relative automation scan (bounded
  // capacity, allocated once with the processor — never on the audio path).
  BlockAutomation blockAutomation_{};

  // float<->double staging (allocated on the main thread at setActive; the
  // audio path only touches the buffers)
  std::vector<double> stagingIn_[2];
  std::vector<double> stagingOut_[2];
  int32_t stagingFrames_ = 0;

  bool initialized_ = false;
};

}  // namespace pitchlab::vst
